prosopon: src/pro_library.c File Reference
src/pro_library.c File Reference
#include "pro_library.h"
#include "prosopon/library.h"
#include "pro_state.h"
#include <dlfcn.h>
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <assert.h>
#include <dirent.h>
#include <unistd.h>
#include <limits.h>
Data Structures
struct pro_library_list
Functions
static int initialize_library (pro_state_ref s, const char *name, void *lib_handle)
static void add_loaded_library (pro_state_ref s, const char *file, void *handle)
static char * get_library_filename (const char *name)
static void * open_library (pro_state_ref s, const char *filename)
PRO_INTERNAL pro_library_list * pro_library_list_new (pro_state_ref s, const char *file, pro_library_list *next)
PRO_INTERNAL int pro_library_loaded (pro_state_ref s, const char *file)
PRO_INTERNAL void pro_library_list_free (pro_state_ref s, pro_library_list *libraries)
PRO_API pro_error pro_library_load (pro_state_ref s, const char *name, const char *lib_name, PRO_OUT void **out_handle)
Function Documentation
static void add_loaded_library (pro_state_ref s, const char * file, void * handle) [static]
References pro_library_list_new(), pro_state_get_libraries(), and pro_state_set_libraries().
static char* get_library_filename (const char * name) [static]
static int initialize_library (pro_state_ref s, const char * name, void * lib_handle) [static]
static void* open_library (pro_state_ref s, const char * filename) [static]
References pro_state::path.
PRO_INTERNAL void pro_library_list_free (pro_state_ref s, pro_library_list * libraries)
References pro_library_list::next, and pro_alloc().
PRO_INTERNAL pro_library_list* pro_library_list_new (pro_state_ref s, const char * file, pro_library_list * next)
Returns:
A new library list.
References pro_library_list::file, pro_library_list::next, and pro_alloc().
PRO_API pro_error pro_library_load (pro_state_ref , const char * name, const char * lib_name, PRO_OUT void ** handle)
Loads and initilizes a Prosopon library.
Parameters:
name The name of the library to load. Must be the library name, such as "std", not the name of the library file.
lib_name The name of the library file to load. Must not include the extension
handle[out]
Returns:
PRO_LIBRARY_LOAD_ERROR If the requested library cannot be found or it does not provide a valid initilization function.
References add_loaded_library(), get_library_filename(), initialize_library(), open_library(), PRO_LIBRARY_LOAD_ERROR, pro_library_loaded(), and PRO_OK.
PRO_INTERNAL int pro_library_loaded (pro_state_ref , const char * file)
Has a library been loaded.
Returns:
0 if false else true
References pro_library_list::next, and pro_state_get_libraries().