prosopon: src/pro_state.c File Reference
src/pro_state.c File Reference
#include "pro_state.h"
#include "pro_type.h"
#include "pro_common.h"
#include "pro_messaging.h"
#include "pro_message_queue.h"
#include "pro_lookup.h"
#include "pro_library.h"
Functions
static pro_state * pro_state_new (pro_alloc_impl *alloc, void *alloc_ud)
static void pro_state_free (pro_state *s)
PRO_INTERNAL struct
pro_library_list * pro_state_get_libraries (pro_state *s)
PRO_INTERNAL void pro_state_set_libraries (pro_state *s, struct pro_library_list *val)
PRO_INTERNAL struct
pro_actor_type_info_list * pro_state_get_actor_type_info (pro_state *s)
PRO_INTERNAL void pro_state_set_actor_type_info (pro_state *s, struct pro_actor_type_info_list *val)
PRO_API pro_error pro_state_create (pro_alloc_impl *alloc, void *alloc_ud, const char **path, PRO_OUT pro_state_ref *out_state)
PRO_API pro_error pro_state_release (pro_state_ref s)
PRO_API void * pro_alloc (pro_state_ref s, void *ptr, size_t size)
PRO_API pro_error pro_run (pro_state_ref s)
Function Documentation
PRO_API void* pro_alloc (pro_state_ref s, void * ptr, size_t size)
See also:
pro_alloc_impl
References pro_state::alloc, and pro_state::alloc_ud.
PRO_API pro_error pro_run (pro_state_ref)
TODO: remove
References pro_state::message_queue, pro_deliver_message(), pro_message_queue_dequeue(), pro_message_queue_is_empty(), PRO_OK, and pro_release().
PRO_API pro_error pro_state_create (pro_alloc_impl * alloc, void * alloc_ud, const char ** path, PRO_OUT pro_state_ref * state)
Creates a new execution state.
Parameters:
alloc Memory management function used to allocate and free all memory.
alloc_ud Userdata that is passed to the allocator.
path Array of paths to search for libraries.
[out] state The newly created state.
Returns:
Does not return PRO_INVALID_STATE PRO_OUT_OF_MEMORY if a new state cannot be allocated.
References initialize_default_actor_types(), pro_state::path, PRO_API_ASSERT, PRO_OK, PRO_OUT_OF_MEMORY, and pro_state_new().
static void pro_state_free (pro_state * s) [static]
References pro_state::actor_types, pro_state::alloc, pro_state::alloc_ud, pro_state::libraries, pro_state::message_queue, pro_actor_type_info_list_free(), pro_library_list_free(), and pro_message_queue_free().
PRO_INTERNAL struct pro_actor_type_info_list* pro_state_get_actor_type_info (pro_state * s) [read]
References pro_state::actor_types.
PRO_INTERNAL struct pro_library_list* pro_state_get_libraries (pro_state *) [read]
Returns:
The list of loaded libraries.
References pro_state::libraries.
static pro_state* pro_state_new (pro_alloc_impl * alloc, void * alloc_ud) [static]
References pro_state::actor_types, pro_state::alloc, pro_state::alloc_ud, pro_state::libraries, pro_state::message_queue, and pro_message_queue_new().
PRO_API pro_error pro_state_release (pro_state_ref)
Releases a state for future collection.
References PRO_API_ASSERT_STATE, PRO_OK, and pro_state_free().
PRO_INTERNAL void pro_state_set_actor_type_info (pro_state * s, struct pro_actor_type_info_list * val)
References pro_state::actor_types.
PRO_INTERNAL void pro_state_set_libraries (pro_state * s, struct pro_library_list * val)
References pro_state::libraries.