prosopon: src/pro_message_queue.h File Reference
src/pro_message_queue.h File Reference
#include "prosopon/core.h"
Typedefs
typedef struct pro_message_queue pro_message_queue
Functions
PRO_INTERNAL pro_message_queue * pro_message_queue_new (pro_state_ref)
PRO_INTERNAL void pro_message_queue_free (pro_state_ref, pro_message_queue *)
PRO_INTERNAL void pro_message_queue_enqueue (pro_state_ref, pro_message_queue *, pro_ref msg, pro_ref actor)
PRO_INTERNAL pro_ref pro_message_queue_dequeue (pro_state_ref, pro_message_queue *, PRO_OUT pro_ref *actor)
PRO_INTERNAL int pro_message_queue_is_empty (pro_state_ref, pro_message_queue *)
Typedef Documentation
typedef struct pro_message_queue pro_message_queue
Message queue data structure.
Function Documentation
PRO_INTERNAL pro_ref pro_message_queue_dequeue (pro_state_ref , pro_message_queue * , PRO_OUT pro_ref * actor)
Returns:
The object at the head of the queue or EMPTY_REF if empty.
References pro_message_node::actor, pro_message_queue::front, pro_message_node::message, pro_message_node::next, and pro_alloc().
PRO_INTERNAL void pro_message_queue_enqueue (pro_state_ref , pro_message_queue * , pro_ref msg, pro_ref actor)
Places a message in the message queue.
References pro_message_queue::front, pro_message_node::next, pro_message_node_new(), and pro_retain().
PRO_INTERNAL void pro_message_queue_free (pro_state_ref , pro_message_queue *)
Releases the memory for a message queue.
References pro_message_queue::front, pro_message_node::next, and pro_alloc().
PRO_INTERNAL int pro_message_queue_is_empty (pro_state_ref , pro_message_queue *)
Returns:
Is the message queue empty.
References pro_message_queue::front.
PRO_INTERNAL pro_message_queue* pro_message_queue_new (pro_state_ref)
Returns:
A new empty message queue.
References pro_message_queue::front, and pro_alloc().