prosopon: src/pro_env.c File Reference
src/pro_env.c File Reference
#include "pro_env.h"
#include "pro_common.h"
#include "pro_lookup.h"
#include "pro_env_lookup.h"
#include "pro_binding_map.h"
Data Structures
struct pro_env
Typedefs
typedef struct pro_internal_lookup pro_internal_lookup
typedef struct pro_lookup_binding pro_lookup_binding
Functions
PRO_INTERNAL pro_env * pro_env_new (pro_state_ref s, pro_env_ref parent, unsigned int ref_count)
PRO_INTERNAL void pro_env_free (pro_state_ref s, pro_env *t)
PRO_INTERNAL pro_env * pro_internal_env_retain (pro_state_ref s, pro_env *t)
PRO_INTERNAL void pro_internal_env_release (pro_state_ref s, pro_env *t)
PRO_INTERNAL void pro_env_unbind_all (pro_state_ref s, pro_env *t)
PRO_API pro_error pro_env_create (pro_state_ref s, pro_env_ref parent, PRO_OUT pro_env_ref *env_out)
PRO_API pro_error pro_bind (pro_state_ref s, pro_ref ref, const char *id)
PRO_API pro_error pro_get_binding (pro_state_ref s, pro_env_ref env_ref, const char *name, PRO_OUT pro_ref *ref)
Typedef Documentation
typedef struct pro_internal_lookup pro_internal_lookup
typedef struct pro_lookup_binding pro_lookup_binding
Function Documentation
PRO_API pro_error pro_bind (pro_state_ref , pro_ref ref, const char * id)
Binds a lookup to an identifier name.
Returns:
PRO_INVALID_OPERATION if ref is PRO_EMPTY_REF. PRO_OUT_OF_MEMORY if memory cannot be allocated.
References pro_env::bindings, PRO_API_ASSERT, PRO_API_ASSERT_STATE, pro_binding_map_new(), pro_binding_map_put(), pro_env_dereference(), pro_env_release(), pro_get_env(), PRO_INVALID_OPERATION, PRO_OK, and pro_retain().
PRO_API pro_error pro_env_create (pro_state_ref , pro_env_ref parent, PRO_OUT pro_env_ref * env)
Creates a new environment with a given parent.
Parameters:
[out] env A reference to the new environment.
Returns:
PRO_OUT_OF_MEMORY if memory cannot be alocated.
References PRO_API_ASSERT, PRO_API_ASSERT_STATE, pro_env_lookup_new(), pro_env_new(), PRO_OK, and PRO_OUT_OF_MEMORY.
PRO_INTERNAL void pro_env_free (pro_state_ref , pro_env *)
Frees the memory for an env.
References pro_env_unbind_all(), and pro_get_alloc().
PRO_INTERNAL pro_env* pro_env_new (pro_state_ref , pro_env_ref parent, unsigned int ref_count)
Internal function to create a new environment.
Returns:
A newly created environment.
References pro_env::bindings, pro_binding_map_copy(), PRO_EMPTY_ENV_REF, pro_env_dereference(), pro_get_alloc(), and pro_env::ref_count.
PRO_INTERNAL void pro_env_unbind_all (pro_state_ref , pro_env *)
Releases all of an env's bindings.
References pro_env::bindings, and pro_binding_map_free().
PRO_API pro_error pro_get_binding (pro_state_ref , pro_env_ref env, const char * name, PRO_OUT pro_ref * ref)
Resolves an identifier to a object.
Parameters:
[out] ref The highest resolved reference or PRO_EMPTY_REF if none. Increments the reference count of the ref.
References pro_env::bindings, PRO_API_ASSERT, PRO_API_ASSERT_STATE, pro_binding_map_get(), PRO_EMPTY_ENV_REF, PRO_EMPTY_REF, pro_env_dereference(), PRO_INVALID_OPERATION, and PRO_OK.
PRO_INTERNAL void pro_internal_env_release (pro_state_ref s, pro_env *)
Releases a pro_env.
References pro_env_free(), and pro_env::ref_count.
PRO_INTERNAL pro_env* pro_internal_env_retain (pro_state_ref s, pro_env *)
Retains an pro_env for further use.
References pro_env::ref_count.