prosopon: src/pro_lookup_table.h File Reference
src/pro_lookup_table.h File Reference
#include "prosopon/core.h"
Typedefs
typedef struct pro_lookup_table pro_lookup_table
Functions
PRO_INTERNAL pro_lookup_table * pro_lookup_table_new (pro_state_ref s)
PRO_INTERNAL void pro_lookup_table_free (pro_state_ref s, pro_lookup_table *t)
PRO_INTERNAL unsigned int pro_lookup_table_add (pro_state_ref s, pro_lookup_table *t)
PRO_INTERNAL void pro_lookup_table_remove (pro_state_ref s, pro_lookup_table *t, unsigned int index)
PRO_INTERNAL struct pro_object ** pro_lookup_table_get (pro_state_ref, pro_lookup_table *t, unsigned int index)
Typedef Documentation
typedef struct pro_lookup_table pro_lookup_table
Lookup table structure.
Function Documentation
PRO_INTERNAL unsigned int pro_lookup_table_add (pro_state_ref s, pro_lookup_table * t)
Reserves a slot for an item in the lookup table and returns the index of this spot.
References pro_internal_lookup_new(), pro_lookup_table::size, and pro_lookup_table::value.
PRO_INTERNAL void pro_lookup_table_free (pro_state_ref s, pro_lookup_table * t)
Releases a lookup table's memory
References pro_internal_lookup::next, pro_get_alloc(), and pro_lookup_table::value.
PRO_INTERNAL struct pro_object** pro_lookup_table_get (pro_state_ref , pro_lookup_table * t, unsigned int index) [read]
References pro_internal_lookup::next, and pro_lookup_table::value.
PRO_INTERNAL pro_lookup_table* pro_lookup_table_new (pro_state_ref s)
Returns:
A new, empty lookup table.
References pro_get_alloc(), pro_lookup_table::size, and pro_lookup_table::value.
PRO_INTERNAL void pro_lookup_table_remove (pro_state_ref s, pro_lookup_table * t, unsigned int index)
Removes a slot from the lookup table.
References pro_internal_lookup::next, pro_get_alloc(), and pro_lookup_table::value.