prosopon: src/pro_list.c File Reference
src/pro_list.c File Reference
#include "prosopon/core.h"
#include "pro_common.h"
#include "pro_object.h"
#include "pro_lookup.h"
#include "pro_lookup_list.h"
Functions
PRO_API pro_error pro_list_create (pro_state_ref s, PRO_OUT pro_ref *msg)
PRO_API pro_error pro_list_length (pro_state_ref s, pro_ref ref, PRO_OUT unsigned int *length)
PRO_API pro_error pro_list_get (pro_state_ref s, pro_ref msg, unsigned int idx, PRO_OUT pro_ref *result)
PRO_API pro_error pro_list_append (pro_state_ref s, pro_ref msg, pro_ref ref, PRO_OUT pro_ref *new_msg_out)
Function Documentation
PRO_API pro_error pro_list_append (pro_state_ref , pro_ref msg, pro_ref value, PRO_OUT pro_ref * new_msg)
Appends an value to a list to create a new list.
Does not modify the origin list.
Parameters:
[out] new_msg A reference to the new list with the new object appended with a reference count of 1. Should not be the same as msg, this will cause a memork leak.
Returns:
PRO_OK if successful PRO_INVALID_STATE if msg does not reference a list or value does not reference a valid object.
References pro_object::message, PRO_API_ASSERT, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, pro_list_create(), PRO_LIST_TYPE, pro_lookup_list_append(), pro_lookup_list_copy(), pro_lookup_list_new(), PRO_OK, pro_retain(), and pro_object::value.
PRO_API pro_error pro_list_create (pro_state_ref , PRO_OUT pro_ref * msg)
Creates a new list.
Parameters:
[out] msg A referance to the new list with a reference count of 1.
Returns:
PRO_OK if successful PRO_INVALID_STATE PRO_OUT_OF_MEMORY if memory allocation fails.
References pro_object::message, PRO_API_ASSERT, PRO_API_ASSERT_STATE, PRO_LIST_TYPE, pro_lookup_new(), pro_object_new(), PRO_OK, PRO_OUT_OF_MEMORY, and pro_object::value.
PRO_API pro_error pro_list_get (pro_state_ref , pro_ref msg, unsigned int index, PRO_OUT pro_ref * result)
Get a value from a list.
Parameters:
[out] result Referance at index or PRO_EMPTY_REF if out of bounds. Retains the refence.
Returns:
PRO_OK if successful PRO_INVALID_STATE If msg does not reference a list.
References pro_object::message, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, PRO_LIST_TYPE, pro_lookup_list_get(), PRO_OK, pro_retain(), and pro_object::value.
PRO_API pro_error pro_list_length (pro_state_ref , pro_ref msg, PRO_OUT unsigned int * length)
Get the number of objects in a list.
Parameters:
[out] length The number of objects a list contains.
Returns:
PRO_OK if successful PRO_INVALID_STATE if msg does not reference a list.
References pro_object::message, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, PRO_LIST_TYPE, pro_lookup_list_length(), PRO_OK, and pro_object::value.