prosopon: src/pro_message_queue.c File Reference
src/pro_message_queue.c File Reference
#include "pro_message_queue.h"
Data Structures
struct pro_message_queue
struct pro_message_node
Typedefs
typedef struct pro_message_node pro_message_node
Functions
static pro_message_node * pro_message_node_new (pro_state_ref s, pro_ref message, pro_ref actor, pro_message_node *next)
PRO_INTERNAL pro_message_queue * pro_message_queue_new (pro_state_ref s)
PRO_INTERNAL void pro_message_queue_free (pro_state_ref s, pro_message_queue *t)
PRO_INTERNAL void pro_message_queue_enqueue (pro_state_ref s, pro_message_queue *t, pro_ref msg, pro_ref actor)
PRO_INTERNAL pro_ref pro_message_queue_dequeue (pro_state_ref s, pro_message_queue *t, PRO_OUT pro_ref *actor)
PRO_INTERNAL int pro_message_queue_is_empty (pro_state_ref s, pro_message_queue *t)
Typedef Documentation
typedef struct pro_message_node pro_message_node
Function Documentation
static pro_message_node* pro_message_node_new (pro_state_ref s, pro_ref message, pro_ref actor, pro_message_node * next) [static]
References pro_message_node::actor, pro_message_node::message, pro_message_node::next, and pro_alloc().
PRO_INTERNAL pro_ref pro_message_queue_dequeue (pro_state_ref , pro_message_queue * , PRO_OUT pro_ref * actor)
Returns:
The object at the head of the queue or EMPTY_REF if empty.
References pro_message_node::actor, pro_message_queue::front, pro_message_node::message, pro_message_node::next, and pro_alloc().
PRO_INTERNAL void pro_message_queue_enqueue (pro_state_ref , pro_message_queue * , pro_ref msg, pro_ref actor)
Places a message in the message queue.
References pro_message_queue::front, pro_message_node::next, pro_message_node_new(), and pro_retain().
PRO_INTERNAL void pro_message_queue_free (pro_state_ref , pro_message_queue *)
Releases the memory for a message queue.
References pro_message_queue::front, pro_message_node::next, and pro_alloc().
PRO_INTERNAL int pro_message_queue_is_empty (pro_state_ref , pro_message_queue *)
Returns:
Is the message queue empty.
References pro_message_queue::front.
PRO_INTERNAL pro_message_queue* pro_message_queue_new (pro_state_ref)
Returns:
A new empty message queue.
References pro_message_queue::front, and pro_alloc().