prosopon: src/pro_type.h File Reference
src/pro_type.h File Reference
#include "prosopon/core.h"
#include <prosopon/actor_type.h>
Data Structures
struct pro_actor_type_info_list
Typedefs
typedef struct
pro_actor_type_info_list pro_actor_type_info_list
Functions
PRO_INTERNAL void initialize_default_actor_types (pro_state_ref)
PRO_INTERNAL
pro_actor_type_info_list * pro_actor_type_info_list_new (pro_state_ref, pro_actor_type type, const pro_actor_type_info *value, pro_actor_type_info_list *next)
PRO_INTERNAL void pro_actor_type_info_list_free (pro_state_ref, pro_actor_type_info_list *)
PRO_INTERNAL const
pro_actor_type_info * pro_get_actor_type_info (pro_state_ref, pro_actor_type type)
Typedef Documentation
typedef struct pro_actor_type_info_list pro_actor_type_info_list
Function Documentation
PRO_INTERNAL void initialize_default_actor_types (pro_state_ref)
References PRO_DEFAULT_ACTOR_TYPE, and pro_register_actor_type().
PRO_INTERNAL void pro_actor_type_info_list_free (pro_state_ref , pro_actor_type_info_list *)
References pro_actor_type_info_list::next, and pro_alloc().
PRO_INTERNAL pro_actor_type_info_list* pro_actor_type_info_list_new (pro_state_ref , pro_actor_type type, const pro_actor_type_info * value, pro_actor_type_info_list * next)
References pro_actor_type_info_list::next, pro_alloc(), pro_actor_type_info_list::type, and pro_actor_type_info_list::value.
PRO_INTERNAL const pro_actor_type_info* pro_get_actor_type_info (pro_state_ref , pro_actor_type type)
References pro_actor_type_info_list::next, pro_state_get_actor_type_info(), pro_actor_type_info_list::type, and pro_actor_type_info_list::value.