prosopon: src/pro_library.h File Reference
src/pro_library.h File Reference
#include "prosopon/core.h"
Typedefs
typedef struct pro_library_list pro_library_list
Functions
PRO_INTERNAL pro_library_list * pro_library_list_new (pro_state_ref s, const char *file, pro_library_list *next)
PRO_INTERNAL int pro_library_loaded (pro_state_ref, const char *file)
PRO_INTERNAL void pro_library_list_free (pro_state_ref, pro_library_list *)
Typedef Documentation
typedef struct pro_library_list pro_library_list
Function Documentation
PRO_INTERNAL void pro_library_list_free (pro_state_ref , pro_library_list *)
References pro_library_list::next, and pro_alloc().
PRO_INTERNAL pro_library_list* pro_library_list_new (pro_state_ref s, const char * file, pro_library_list * next)
Returns:
A new library list.
References pro_library_list::file, pro_library_list::next, and pro_alloc().
PRO_INTERNAL int pro_library_loaded (pro_state_ref , const char * file)
Has a library been loaded.
Returns:
0 if false else true
References pro_library_list::next, and pro_state_get_libraries().