prosopon: src/pro_type.c File Reference
src/pro_type.c File Reference
#include "pro_type.h"
#include "pro_state.h"
#include <string.h>
#include <stdio.h>
Functions
static pro_matching default_match (pro_state_ref s, pro_ref t, pro_ref tData, pro_ref o, pro_ref oData)
static pro_ref default_to_string (pro_state_ref s, pro_ref t, pro_ref tData)
PRO_INTERNAL
pro_actor_type_info_list * pro_actor_type_info_list_new (pro_state_ref s, pro_actor_type type, const pro_actor_type_info *value, pro_actor_type_info_list *next)
PRO_INTERNAL void pro_actor_type_info_list_free (pro_state_ref s, pro_actor_type_info_list *t)
PRO_INTERNAL void initialize_default_actor_types (pro_state_ref s)
PRO_INTERNAL const
pro_actor_type_info * pro_get_actor_type_info (pro_state_ref s, pro_actor_type type)
PRO_API void pro_register_actor_type (pro_state_ref s, const char *identifier, const pro_actor_type_info *info)
Variables
static const pro_actor_type_info pro_default_actor_type_info
pro_actor_type PRO_DEFAULT_ACTOR_TYPE = 0
Function Documentation
static pro_matching default_match (pro_state_ref s, pro_ref t, pro_ref tData, pro_ref o, pro_ref oData) [static]
References PRO_MATCH_FAIL.
static pro_ref default_to_string (pro_state_ref s, pro_ref t, pro_ref tData) [static]
References PRO_DEFAULT_UD_DECONSTRUCTOR(), pro_ud_create(), and pro_ud_write().
PRO_INTERNAL void initialize_default_actor_types (pro_state_ref s)
References PRO_DEFAULT_ACTOR_TYPE, and pro_register_actor_type().
PRO_INTERNAL void pro_actor_type_info_list_free (pro_state_ref s, pro_actor_type_info_list * t)
References pro_actor_type_info_list::next, and pro_alloc().
PRO_INTERNAL pro_actor_type_info_list* pro_actor_type_info_list_new (pro_state_ref s, pro_actor_type type, const pro_actor_type_info * value, pro_actor_type_info_list * next)
References pro_actor_type_info_list::next, pro_alloc(), pro_actor_type_info_list::type, and pro_actor_type_info_list::value.
PRO_INTERNAL const pro_actor_type_info* pro_get_actor_type_info (pro_state_ref s, pro_actor_type type)
References pro_actor_type_info_list::next, pro_state_get_actor_type_info(), pro_actor_type_info_list::type, and pro_actor_type_info_list::value.
PRO_API void pro_register_actor_type (pro_state_ref s, const char * identifier, const pro_actor_type_info * info)
References pro_actor_type_info_list::next, pro_actor_type_info_list_new(), pro_state_get_actor_type_info(), and pro_state_set_actor_type_info().
Variable Documentation
pro_actor_type PRO_DEFAULT_ACTOR_TYPE = 0
const pro_actor_type_info pro_default_actor_type_info [static]
Initial value:
 {
    .match = default_match,
    .to_string = default_to_string
}