prosopon: src/pro_lookup_list.h File Reference
src/pro_lookup_list.h File Reference
#include "prosopon/core.h"
Typedefs
typedef struct pro_lookup_list * pro_ref_list
Functions
PRO_INTERNAL pro_ref_list pro_lookup_list_new (pro_state_ref)
PRO_INTERNAL pro_ref_list pro_lookup_list_copy (pro_state_ref s, const pro_ref_list cpy)
PRO_INTERNAL void pro_lookup_list_free (pro_state_ref, pro_ref_list t)
PRO_INTERNAL void pro_lookup_list_append (pro_state_ref, pro_ref_list t, pro_ref value)
PRO_INTERNAL unsigned int pro_lookup_list_length (pro_state_ref s, const pro_ref_list t)
PRO_INTERNAL pro_ref pro_lookup_list_get (pro_state_ref s, const pro_ref_list t, unsigned int idx)
Typedef Documentation
typedef struct pro_lookup_list* pro_ref_list
A list of lookup values.
Function Documentation
PRO_INTERNAL void pro_lookup_list_append (pro_state_ref , pro_ref_list t, pro_ref value)
Appends an referance to a lookup list.
References pro_lookup_list::back, pro_lookup_list::front, pro_lookup_list_node::next, pro_lookup_list_node_new(), and pro_lookup_list::size.
PRO_INTERNAL pro_ref_list pro_lookup_list_copy (pro_state_ref s, const pro_ref_list cpy)
References pro_lookup_list_append(), pro_lookup_list_get(), pro_lookup_list_length(), pro_lookup_list_new(), and pro_retain().
PRO_INTERNAL void pro_lookup_list_free (pro_state_ref , pro_ref_list t)
Deallocates a lookup list.
References pro_lookup_list::front, pro_lookup_list_node::next, pro_alloc(), and pro_release().
PRO_INTERNAL pro_ref pro_lookup_list_get (pro_state_ref s, const pro_ref_list t, unsigned int idx)
References pro_lookup_list::front, pro_lookup_list_node::next, PRO_EMPTY_REF, pro_lookup_list_length(), and pro_lookup_list_node::value.
PRO_INTERNAL unsigned int pro_lookup_list_length (pro_state_ref s, const pro_ref_list t)
References pro_lookup_list::size.
PRO_INTERNAL pro_ref_list pro_lookup_list_new (pro_state_ref)
Returns:
A new lookup list.
References pro_lookup_list::back, pro_lookup_list::front, pro_alloc(), and pro_lookup_list::size.