prosopon: src/pro_env_stack.h File Reference
src/pro_env_stack.h File Reference
#include "prosopon/core.h"
Typedefs
typedef struct pro_env_stack pro_env_stack
Functions
PRO_INTERNAL pro_env_stack * pro_env_stack_new (pro_state_ref)
PRO_INTERNAL void pro_env_stack_free (pro_state_ref, pro_env_stack *)
PRO_INTERNAL void pro_env_stack_push (pro_state_ref, pro_env_stack *, pro_env_ref)
PRO_INTERNAL void pro_env_stack_pop (pro_state_ref, pro_env_stack *)
PRO_INTERNAL pro_env_ref pro_env_stack_top (pro_state_ref, pro_env_stack *)
Typedef Documentation
typedef struct pro_env_stack pro_env_stack
Function Documentation
PRO_INTERNAL void pro_env_stack_free (pro_state_ref , pro_env_stack *)
Frees the memory for an env_stack
References pro_env_stack_node::next, pro_get_alloc(), and pro_env_stack::top.
PRO_INTERNAL pro_env_stack* pro_env_stack_new (pro_state_ref)
Returns:
An new, empty environment stack.
References pro_get_alloc(), and pro_env_stack::top.
PRO_INTERNAL void pro_env_stack_pop (pro_state_ref , pro_env_stack *)
Pops an environemtn off the stack.
References pro_env_stack_node::next, pro_get_alloc(), and pro_env_stack::top.
PRO_INTERNAL void pro_env_stack_push (pro_state_ref , pro_env_stack * , pro_env_ref)
Pushes an environment onto the stack.
References pro_env_stack_node_new(), and pro_env_stack::top.
PRO_INTERNAL pro_env_ref pro_env_stack_top (pro_state_ref , pro_env_stack *)
Returns:
The top environment of the stack.
References pro_env_stack::top, and pro_env_stack_node::value.