prosopon: src/pro_lookup.h File Reference
src/pro_lookup.h File Reference
#include "prosopon/core.h"
Data Structures
struct pro_lookup
Typedefs
typedef struct pro_lookup pro_lookup
Functions
PRO_INTERNAL pro_lookup * pro_lookup_new (pro_state_ref, struct pro_object *obj, unsigned int ref_count)
PRO_INTERNAL void pro_lookup_free (pro_state_ref, pro_lookup *)
PRO_INTERNAL int pro_lookup_equal (pro_state_ref, const pro_lookup *, const pro_lookup *)
PRO_INTERNAL struct pro_object * pro_dereference (pro_state_ref, pro_ref)
Typedef Documentation
typedef struct pro_lookup pro_lookup
Internal structure for pro_ref.
Function Documentation
PRO_INTERNAL struct pro_object* pro_dereference (pro_state_ref , pro_ref) [read]
Dereferenaces a pro_ref to the pro_object it references
References pro_lookup::obj, PRO_EMPTY_REF, and pro_lookup_equal().
PRO_INTERNAL int pro_lookup_equal (pro_state_ref , const pro_lookup * , const pro_lookup *)
Tests if two lookups are equivlent.
Returns:
Zero if false or non zero if true.
PRO_INTERNAL void pro_lookup_free (pro_state_ref , pro_lookup *)
Frees the memory for a lookup.
References pro_alloc(), pro_dereference(), and pro_object_release().
PRO_INTERNAL pro_lookup* pro_lookup_new (pro_state_ref , struct pro_object * obj, unsigned int ref_count)
Returns:
A new lookup.