prosopon: src/pro_user_data.c File Reference
src/pro_user_data.c File Reference
#include "prosopon/core.h"
#include "pro_common.h"
#include "pro_object.h"
#include "pro_lookup.h"
Functions
PRO_API void PRO_DEFAULT_UD_DECONSTRUCTOR (pro_state_ref s, void *data)
PRO_API pro_error pro_ud_create (pro_state_ref s, size_t size, pro_ud_deconstructor *deconstructor, PRO_OUT pro_ref *t)
PRO_API pro_error pro_ud_read (pro_state_ref s, pro_ref t, PRO_OUT const void **ptr)
PRO_API pro_error pro_ud_write (pro_state_ref s, pro_ref t, PRO_OUT void **ptr)
Function Documentation
PRO_API void PRO_DEFAULT_UD_DECONSTRUCTOR (pro_state_ref , void * data)
Default deconstructor called on user data.
Frees the user data pointer.
References pro_alloc().
PRO_API pro_error pro_ud_create (pro_state_ref , size_t size, pro_ud_deconstructor * deconstructor, PRO_OUT pro_ref * out_ref)
Creates a new user data object with a given size and deconstructor.
Parameters:
[out] out_ref A reference to the new user data object with a reference count of 1.
Returns:
PRO_OK if successful PRO_INVALID_STATE PRO_OUT_OF_MEMORY If memory for the requested object cannot be allocated.
References pro_alloc(), PRO_API_ASSERT_STATE, pro_lookup_new(), pro_object_new(), PRO_OK, PRO_UD_TYPE, pro_object::ud, and pro_object::value.
PRO_API pro_error pro_ud_read (pro_state_ref , pro_ref , PRO_OUT const void ** out_data)
Requests access to user data data for reading.
Parameters:
[out] out_data A pointer to the user data memory for reading. Must not be written.
Returns:
PRO_OK if successful PRO_INVALID_STATE if ref is not user data.
References PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, PRO_OK, PRO_UD_TYPE, pro_object::ud, and pro_object::value.
PRO_API pro_error pro_ud_write (pro_state_ref , pro_ref , PRO_OUT void ** out_data)
Requests access to user data data for writting.
Parameters:
[out] out_data A pointer to the user data memory for both writing and reading.
Returns:
PRO_OK if successful PRO_INVALID_STATE if ref is not a valid user data object.
References PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, PRO_OK, PRO_UD_TYPE, pro_object::ud, and pro_object::value.