prosopon: src/pro_lookup.c File Reference
src/pro_lookup.c File Reference
#include "pro_lookup.h"
#include "pro_common.h"
#include "pro_state.h"
#include "pro_object.h"
Functions
PRO_INTERNAL pro_lookup * pro_lookup_new (pro_state *s, struct pro_object *obj, unsigned int ref_count)
PRO_INTERNAL int pro_lookup_equal (pro_state *s, const pro_lookup *o1, const pro_lookup *o2)
PRO_INTERNAL void pro_lookup_free (pro_state_ref s, pro_lookup *t)
PRO_INTERNAL pro_object * pro_dereference (pro_state_ref s, pro_ref ref)
PRO_API pro_error pro_retain (pro_state_ref s, pro_ref ref)
PRO_API pro_error pro_release (pro_state_ref s, pro_ref ref)
Variables
pro_ref PRO_EMPTY_REF = 0
Function Documentation
PRO_INTERNAL pro_object* pro_dereference (pro_state_ref , pro_ref) [read]
Dereferenaces a pro_ref to the pro_object it references
References pro_lookup::obj, PRO_EMPTY_REF, and pro_lookup_equal().
PRO_INTERNAL int pro_lookup_equal (pro_state * s, const pro_lookup * o1, const pro_lookup * o2)
References pro_lookup::obj, and PRO_EMPTY_REF.
PRO_INTERNAL void pro_lookup_free (pro_state_ref , pro_lookup *)
Frees the memory for a lookup.
References pro_alloc(), pro_dereference(), and pro_object_release().
PRO_INTERNAL pro_lookup* pro_lookup_new (pro_state * s, struct pro_object * obj, unsigned int ref_count)
References pro_lookup::obj, pro_alloc(), and pro_lookup::ref_count.
PRO_API pro_error pro_release (pro_state_ref , pro_ref)
Release an referenced object for future collection.
See also:
memory_management.
References PRO_API_ASSERT, PRO_INVALID_OPERATION, pro_lookup_equal(), pro_lookup_free(), PRO_OK, and pro_lookup::ref_count.
PRO_API pro_error pro_retain (pro_state_ref , pro_ref)
Retains a reference for further use.
See also:
memory_management.
References pro_lookup_equal(), PRO_OK, and pro_lookup::ref_count.
Variable Documentation
pro_ref PRO_EMPTY_REF = 0