prosopon: src/pro_env_lookup.h File Reference
src/pro_env_lookup.h File Reference
#include "prosopon/core.h"
Typedefs
typedef struct pro_env_lookup pro_env_lookup
Functions
PRO_INTERNAL pro_env_lookup * pro_env_lookup_new (pro_state_ref, struct pro_env *value, unsigned int ref_count)
PRO_INTERNAL void pro_env_lookup_free (pro_state_ref, pro_env_lookup *)
PRO_INTERNAL int pro_env_lookup_equal (pro_state_ref, const pro_env_lookup *, const pro_env_lookup *)
PRO_INTERNAL struct pro_env * pro_env_dereference (pro_state_ref, pro_env_ref)
Typedef Documentation
typedef struct pro_env_lookup pro_env_lookup
Internal structure for pro_env_ref
Function Documentation
PRO_INTERNAL struct pro_env* pro_env_dereference (pro_state_ref , pro_env_ref) [read]
Dereferenaces a pro_env_ref
References pro_env_lookup::value.
PRO_INTERNAL int pro_env_lookup_equal (pro_state_ref , const pro_env_lookup * , const pro_env_lookup *)
Tests if two env_lookups are equivlent.
Returns:
Zero if false or non zero if true.
References pro_env_lookup::value.
PRO_INTERNAL void pro_env_lookup_free (pro_state_ref , pro_env_lookup *)
Frees an the memory for an env_lookup
References pro_env_dereference(), pro_get_alloc(), and pro_internal_env_release().
PRO_INTERNAL pro_env_lookup* pro_env_lookup_new (pro_state_ref , struct pro_env * value, unsigned int ref_count)
Returns:
A new env lookup.
References pro_get_alloc(), pro_env_lookup::ref_count, and pro_env_lookup::value.