prosopon: src/pro_object.h File Reference
src/pro_object.h File Reference
#include "prosopon/core.h"
Data Structures
struct pro_object
Typedefs
typedef struct pro_object pro_object
Functions
PRO_INTERNAL pro_object * pro_object_new (pro_state_ref, pro_type type, unsigned int ref_count)
PRO_INTERNAL void pro_object_free (pro_state_ref, pro_object *)
PRO_INTERNAL pro_object * pro_object_retain (pro_state_ref, pro_object *)
PRO_INTERNAL void pro_object_release (pro_state_ref, pro_object *)
Typedef Documentation
typedef struct pro_object pro_object
Structure that holds data for all objects.
Function Documentation
PRO_INTERNAL void pro_object_free (pro_state_ref , pro_object *)
Frees the memory for a pro_object.
References pro_object::actor, pro_object::message, PRO_ACTOR_TYPE, pro_alloc(), PRO_LIST_TYPE, pro_lookup_list_free(), pro_release(), PRO_UD_TYPE, pro_object::type, pro_object::ud, and pro_object::value.
PRO_INTERNAL pro_object* pro_object_new (pro_state_ref , pro_type type, unsigned int ref_count)
Allocates a new pro_object of a given type.
Returns:
The newly allocated object
References pro_alloc(), pro_object::ref_count, and pro_object::type.
PRO_INTERNAL void pro_object_release (pro_state_ref , pro_object *)
Releases a pro_object.
When ref count is zero, object can be released. Caller must not use the object after calling release.
References PRO_ASSERT, pro_object_free(), and pro_object::ref_count.
PRO_INTERNAL pro_object* pro_object_retain (pro_state_ref , pro_object *)
Retains a pro_object.
References pro_object::ref_count.