prosopon: src/pro_env.h File Reference
src/pro_env.h File Reference
#include "prosopon/core.h"
Typedefs
typedef struct pro_env pro_env
Functions
PRO_INTERNAL pro_env * pro_env_new (pro_state_ref, pro_env_ref parent, unsigned int ref_count)
PRO_INTERNAL void pro_env_free (pro_state_ref, pro_env *)
PRO_INTERNAL pro_env * pro_internal_env_retain (pro_state_ref s, pro_env *)
PRO_INTERNAL void pro_internal_env_release (pro_state_ref s, pro_env *)
PRO_INTERNAL void pro_env_unbind_all (pro_state_ref, pro_env *)
Typedef Documentation
typedef struct pro_env pro_env
Internal data structure that holds scope information.
Function Documentation
PRO_INTERNAL void pro_env_free (pro_state_ref , pro_env *)
Frees the memory for an env.
References pro_env_unbind_all(), and pro_get_alloc().
PRO_INTERNAL pro_env* pro_env_new (pro_state_ref , pro_env_ref parent, unsigned int ref_count)
Internal function to create a new environment.
Returns:
A newly created environment.
References pro_env::bindings, pro_binding_map_copy(), PRO_EMPTY_ENV_REF, pro_env_dereference(), pro_get_alloc(), and pro_env::ref_count.
PRO_INTERNAL void pro_env_unbind_all (pro_state_ref , pro_env *)
Releases all of an env's bindings.
References pro_env::bindings, and pro_binding_map_free().
PRO_INTERNAL void pro_internal_env_release (pro_state_ref s, pro_env *)
Releases a pro_env.
References pro_env_free(), and pro_env::ref_count.
PRO_INTERNAL pro_env* pro_internal_env_retain (pro_state_ref s, pro_env *)
Retains an pro_env for further use.
References pro_env::ref_count.