prosopon: src/pro_actor.c File Reference
src/pro_actor.c File Reference
#include "prosopon/prosopon.h"
#include "pro_lookup.h"
#include "pro_common.h"
#include "pro_message_queue.h"
#include "pro_state.h"
#include "pro_object.h"
Functions
PRO_API pro_error pro_actor_create (pro_state_ref s, pro_actor_type type, pro_behavior beh, pro_ref data, PRO_OUT pro_ref *out_ref)
PRO_API pro_error pro_get_actor_type (pro_state_ref s, pro_ref actor, PRO_OUT pro_actor_type *out_type)
PRO_API pro_error pro_send (pro_state_ref s, pro_ref actor, pro_ref msg)
PRO_API pro_error pro_become (pro_state_ref s, pro_ref actor, pro_ref new_beh)
PRO_API pro_error pro_actor_request_ud (pro_state_ref s, pro_ref actor, PRO_OUT pro_ref *ud)
Function Documentation
PRO_API pro_error pro_actor_create (pro_state_ref , pro_actor_type type, pro_behavior beh, pro_ref data, PRO_OUT pro_ref * out_ref)
Create a new actor.
Parameters:
type The actor type of the new actor. Determines primitive functions.
beh The behavior for the new actor. May be null.
data A reference to user data for the actor. May be PRO_EMPTY_REF.
[out] out_ref The lookup for the new actor with a reference count of 1.
Returns:
PRO_OK if successful PRO_INVALID_STATE
References pro_object::actor, pro_lookup::obj, PRO_ACTOR_TYPE, PRO_API_ASSERT_STATE, pro_lookup_new(), pro_object_new(), PRO_OK, pro_retain(), and pro_object::value.
PRO_API pro_error pro_actor_request_ud (pro_state_ref s, pro_ref actor, PRO_OUT pro_ref * ud)
References pro_object::actor, pro_lookup::obj, PRO_ACTOR_TYPE, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, PRO_OK, and pro_object::value.
PRO_API pro_error pro_become (pro_state_ref , pro_ref actor, pro_ref new_beh)
Specify the behavior for an actor.
Essentially sets up message forwarding from the old actor to the new actor. Usually, 'become' forwards messages to a newly created actor but this is not required.
Parameters:
actor The actor we a specifying the new behavior for.
new_beh The actor that will recieve all messages from the old actor.
Returns:
PRO_OK if successful PRO_INVALID_STATE if either actor or new_beh are not valid actors.
References pro_lookup::obj, PRO_ACTOR_TYPE, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, pro_object_release(), pro_object_retain(), and PRO_OK.
PRO_API pro_error pro_get_actor_type (pro_state_ref , pro_ref , PRO_OUT pro_actor_type * out_type)
Parameters:
[out] out_type The actor type of a lookup.
Returns:
PRO_OK if successful PRO_INVALID_STATE if ref is not a valid actor.
References pro_object::actor, pro_lookup::obj, PRO_ACTOR_TYPE, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_INVALID_OPERATION, PRO_OK, and pro_object::value.
PRO_API pro_error pro_send (pro_state_ref , pro_ref actor, pro_ref msg)
Sends a message to an actor asynchronously.
Parameters:
actor A reference to the actor that is sent the message or PRO_EMPTY_REF. PRO_EMPTY_REF acts as a message sink.
msg A reference to be sent to the actor. May be a reference for any type or PRO_EMPTY_TYPE.
Returns:
PRO_OK if successful PRO_INVALID_STATE if actor is not a valid actor.
References pro_state::message_queue, PRO_ACTOR_TYPE, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, PRO_EMPTY_REF, PRO_INVALID_OPERATION, PRO_LIST_TYPE, pro_lookup_equal(), pro_message_queue_enqueue(), and PRO_OK.