prosopon: src/pro_lookup_table.c File Reference
src/pro_lookup_table.c File Reference
#include "pro_lookup_table.h"
#include "pro_object.h"
Data Structures
struct pro_lookup_table
struct pro_internal_lookup
Typedefs
typedef struct pro_internal_lookup pro_internal_lookup
Functions
static pro_internal_lookup * pro_internal_lookup_new (pro_state_ref s, pro_object *value, pro_internal_lookup *next, unsigned int index)
PRO_INTERNAL pro_lookup_table * pro_lookup_table_new (pro_state_ref s)
PRO_INTERNAL void pro_lookup_table_free (pro_state_ref s, pro_lookup_table *t)
PRO_INTERNAL unsigned int pro_lookup_table_add (pro_state_ref s, pro_lookup_table *t)
PRO_INTERNAL void pro_lookup_table_remove (pro_state_ref s, pro_lookup_table *t, unsigned int index)
PRO_INTERNAL pro_object ** pro_lookup_table_get (pro_state_ref s, pro_lookup_table *t, unsigned int index)
Typedef Documentation
typedef struct pro_internal_lookup pro_internal_lookup
Function Documentation
static pro_internal_lookup* pro_internal_lookup_new (pro_state_ref s, pro_object * value, pro_internal_lookup * next, unsigned int index) [static]
Creates a new internal lookup.
Returns:
The new internal lookup.
References pro_internal_lookup::index, and pro_get_alloc().
PRO_INTERNAL unsigned int pro_lookup_table_add (pro_state_ref s, pro_lookup_table * t)
Reserves a slot for an item in the lookup table and returns the index of this spot.
References pro_internal_lookup_new(), pro_lookup_table::size, and pro_lookup_table::value.
PRO_INTERNAL void pro_lookup_table_free (pro_state_ref s, pro_lookup_table * t)
Releases a lookup table's memory
References pro_internal_lookup::next, pro_get_alloc(), and pro_lookup_table::value.
PRO_INTERNAL pro_object** pro_lookup_table_get (pro_state_ref s, pro_lookup_table * t, unsigned int index) [read]
References pro_internal_lookup::next, and pro_lookup_table::value.
PRO_INTERNAL pro_lookup_table* pro_lookup_table_new (pro_state_ref s)
Returns:
A new, empty lookup table.
References pro_get_alloc(), pro_lookup_table::size, and pro_lookup_table::value.
PRO_INTERNAL void pro_lookup_table_remove (pro_state_ref s, pro_lookup_table * t, unsigned int index)
Removes a slot from the lookup table.
References pro_internal_lookup::next, pro_get_alloc(), and pro_lookup_table::value.