prosopon: src/pro_binding_map.c File Reference
src/pro_binding_map.c File Reference
#include "pro_binding_map.h"
#include <string.h>
Data Structures
struct pro_binding_map
struct pro_lookup_binding
Typedefs
typedef struct pro_lookup_binding pro_lookup_binding
Functions
static pro_lookup_binding * pro_lookup_binding_new (pro_state_ref s, const char *identifier, pro_ref lookup, pro_lookup_binding *next)
static void pro_lookup_binding_free (pro_alloc *alloc, pro_lookup_binding *t)
PRO_INTERNAL pro_binding_map * pro_binding_map_new (pro_state_ref s)
PRO_INTERNAL pro_binding_map * pro_binding_map_copy (pro_state_ref s, pro_binding_map *c)
PRO_INTERNAL void pro_binding_map_free (pro_state_ref s, pro_binding_map *t)
PRO_INTERNAL pro_ref pro_binding_map_get (pro_state_ref s, pro_binding_map *t, const char *name)
PRO_INTERNAL void pro_binding_map_put (pro_state_ref s, pro_binding_map *t, const char *name, pro_ref ref)
Typedef Documentation
typedef struct pro_lookup_binding pro_lookup_binding
Function Documentation
PRO_INTERNAL pro_binding_map* pro_binding_map_copy (pro_state_ref s, pro_binding_map * c)
Returns:
A new binding map or null if alloc failed.
References pro_lookup_binding::next, pro_binding_map_new(), pro_binding_map_put(), pro_retain(), and pro_binding_map::value.
PRO_INTERNAL void pro_binding_map_free (pro_state_ref s, pro_binding_map *)
Releases a binding map.
References pro_lookup_binding::next, pro_get_alloc(), pro_lookup_binding_free(), pro_release(), and pro_binding_map::value.
PRO_INTERNAL pro_ref pro_binding_map_get (pro_state_ref s, pro_binding_map * , const char *)
Lookup the bound value for an identifier.
Returns:
The result or PRO_EMPTY_REF if not found
References pro_lookup_binding::next, PRO_EMPTY_REF, pro_retain(), and pro_binding_map::value.
PRO_INTERNAL pro_binding_map* pro_binding_map_new (pro_state_ref s)
Returns:
A new binding map or null if alloc failed.
References pro_get_alloc(), and pro_binding_map::value.
PRO_INTERNAL void pro_binding_map_put (pro_state_ref s, pro_binding_map * , const char * , pro_ref)
Sets the binding for an identifier.
References pro_lookup_binding_new(), and pro_binding_map::value.
static void pro_lookup_binding_free (pro_alloc * alloc, pro_lookup_binding * t) [static]
References pro_lookup_binding::identifier.
static pro_lookup_binding* pro_lookup_binding_new (pro_state_ref s, const char * identifier, pro_ref lookup, pro_lookup_binding * next) [static]
References pro_lookup_binding::identifier, and pro_get_alloc().