prosopon: src/pro_object.c File Reference
src/pro_object.c File Reference
#include "pro_object.h"
#include "pro_type.h"
#include "pro_common.h"
#include "pro_lookup.h"
#include "pro_lookup_list.h"
Functions
PRO_INTERNAL pro_object * pro_object_new (pro_state_ref s, pro_type type, unsigned int ref_count)
PRO_INTERNAL void pro_object_free (pro_state_ref s, pro_object *t)
PRO_INTERNAL pro_object * pro_object_retain (pro_state_ref s, pro_object *t)
PRO_INTERNAL void pro_object_release (pro_state_ref s, pro_object *t)
PRO_API pro_error pro_get_type (pro_state_ref s, pro_ref ref, PRO_OUT pro_type *type)
PRO_API pro_error pro_match (pro_state_ref s, pro_ref l1, pro_ref l2, PRO_OUT pro_matching *out)
PRO_API pro_error pro_to_string (pro_state_ref s, pro_ref t, PRO_OUT pro_ref *ud)
Function Documentation
PRO_API pro_error pro_get_type (pro_state_ref , pro_ref lookup, PRO_OUT pro_type * type)
Parameters:
[out] type The type value of a lookup.
References PRO_API_ASSERT, PRO_API_ASSERT_STATE, pro_dereference(), PRO_EMPTY_REF, PRO_INVALID_OPERATION, pro_lookup_equal(), PRO_OK, and pro_object::type.
PRO_API pro_error pro_match (pro_state_ref , pro_ref , pro_ref ref, PRO_OUT pro_matching * match)
Attempts to match two identifiers.
Parameters:
[out] match One if the two items match else zero.
Returns:
PRO_OK if successful PRO_INVALID_OPERATION if the state is not valid or id is null.
References pro_object::actor, pro_actor_type_info::match, PRO_ACTOR_TYPE, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, pro_dereference(), PRO_EMPTY_REF, pro_get_actor_type(), pro_get_actor_type_info(), PRO_INVALID_OPERATION, pro_lookup_equal(), PRO_MATCH_FAIL, PRO_MATCH_SUCCEED, PRO_OK, and pro_object::value.
PRO_INTERNAL void pro_object_free (pro_state_ref , pro_object *)
Frees the memory for a pro_object.
References pro_object::actor, pro_object::message, PRO_ACTOR_TYPE, pro_alloc(), PRO_LIST_TYPE, pro_lookup_list_free(), pro_release(), PRO_UD_TYPE, pro_object::type, pro_object::ud, and pro_object::value.
PRO_INTERNAL pro_object* pro_object_new (pro_state_ref , pro_type type, unsigned int ref_count)
Allocates a new pro_object of a given type.
Returns:
The newly allocated object
References pro_alloc(), pro_object::ref_count, and pro_object::type.
PRO_INTERNAL void pro_object_release (pro_state_ref , pro_object *)
Releases a pro_object.
When ref count is zero, object can be released. Caller must not use the object after calling release.
References PRO_ASSERT, pro_object_free(), and pro_object::ref_count.
PRO_INTERNAL pro_object* pro_object_retain (pro_state_ref , pro_object *)
Retains a pro_object.
References pro_object::ref_count.
PRO_API pro_error pro_to_string (pro_state_ref , pro_ref , PRO_OUT pro_ref * ud)
Gets the string representation of an object.
Parameters:
[out] ud User data with a reference count of one to store the object.
References pro_object::actor, pro_dereference(), pro_get_actor_type(), pro_get_actor_type_info(), PRO_OK, pro_actor_type_info::to_string, and pro_object::value.