prosopon: src/pro_env_lookup.c File Reference
src/pro_env_lookup.c File Reference
#include "pro_env_lookup.h"
#include "pro_common.h"
#include "pro_env.h"
Data Structures
struct pro_env_lookup
Functions
PRO_INTERNAL pro_env_lookup * pro_env_lookup_new (pro_state_ref s, struct pro_env *value, unsigned int ref_count)
PRO_INTERNAL void pro_env_lookup_free (pro_state_ref s, pro_env_lookup *t)
PRO_INTERNAL int pro_env_lookup_equal (pro_state_ref s, const pro_env_lookup *o1, const pro_env_lookup *o2)
PRO_INTERNAL pro_env * pro_env_dereference (pro_state_ref s, pro_env_ref env_ref)
PRO_API pro_error pro_env_retain (pro_state_ref s, pro_env_ref env_ref)
PRO_API pro_error pro_env_release (pro_state_ref s, pro_env_ref env_ref)
Variables
pro_env_ref PRO_EMPTY_ENV_REF = 0
Function Documentation
PRO_INTERNAL pro_env* pro_env_dereference (pro_state_ref , pro_env_ref) [read]
Dereferenaces a pro_env_ref
References pro_env_lookup::value.
PRO_INTERNAL int pro_env_lookup_equal (pro_state_ref , const pro_env_lookup * , const pro_env_lookup *)
Tests if two env_lookups are equivlent.
Returns:
Zero if false or non zero if true.
References pro_env_lookup::value.
PRO_INTERNAL void pro_env_lookup_free (pro_state_ref , pro_env_lookup *)
Frees an the memory for an env_lookup
References pro_env_dereference(), pro_get_alloc(), and pro_internal_env_release().
PRO_INTERNAL pro_env_lookup* pro_env_lookup_new (pro_state_ref , struct pro_env * value, unsigned int ref_count)
Returns:
A new env lookup.
References pro_get_alloc(), pro_env_lookup::ref_count, and pro_env_lookup::value.
PRO_API pro_error pro_env_release (pro_state_ref , pro_env_ref)
Release an environment for future collection.
See also:
memory_management.
References pro_env_lookup_free(), PRO_OK, and pro_env_lookup::ref_count.
PRO_API pro_error pro_env_retain (pro_state_ref , pro_env_ref)
Retains a env reference for further use.
See also:
memory_management.
References PRO_API_ASSERT_STATE, PRO_OK, and pro_env_lookup::ref_count.
Variable Documentation
pro_env_ref PRO_EMPTY_ENV_REF = 0