prosopon: src/pro_env_stack.c File Reference
src/pro_env_stack.c File Reference
#include "pro_env_stack.h"
Data Structures
struct pro_env_stack_node
struct pro_env_stack
Typedefs
typedef struct pro_env_stack_node pro_env_stack_node
Functions
static pro_env_stack_node * pro_env_stack_node_new (pro_state_ref s, pro_env_ref value, pro_env_stack_node *next)
PRO_INTERNAL pro_env_stack * pro_env_stack_new (pro_state_ref s)
PRO_INTERNAL void pro_env_stack_free (pro_state_ref s, pro_env_stack *t)
PRO_INTERNAL void pro_env_stack_push (pro_state_ref s, pro_env_stack *t, pro_env_ref v)
PRO_INTERNAL void pro_env_stack_pop (pro_state_ref s, pro_env_stack *t)
PRO_INTERNAL pro_env_ref pro_env_stack_top (pro_state_ref s, pro_env_stack *t)
Typedef Documentation
typedef struct pro_env_stack_node pro_env_stack_node
Function Documentation
PRO_INTERNAL void pro_env_stack_free (pro_state_ref , pro_env_stack *)
Frees the memory for an env_stack
References pro_env_stack_node::next, pro_get_alloc(), and pro_env_stack::top.
PRO_INTERNAL pro_env_stack* pro_env_stack_new (pro_state_ref)
Returns:
An new, empty environment stack.
References pro_get_alloc(), and pro_env_stack::top.
static pro_env_stack_node* pro_env_stack_node_new (pro_state_ref s, pro_env_ref value, pro_env_stack_node * next) [static]
References pro_env_stack_node::next, pro_get_alloc(), and pro_env_stack_node::value.
PRO_INTERNAL void pro_env_stack_pop (pro_state_ref , pro_env_stack *)
Pops an environemtn off the stack.
References pro_env_stack_node::next, pro_get_alloc(), and pro_env_stack::top.
PRO_INTERNAL void pro_env_stack_push (pro_state_ref , pro_env_stack * , pro_env_ref)
Pushes an environment onto the stack.
References pro_env_stack_node_new(), and pro_env_stack::top.
PRO_INTERNAL pro_env_ref pro_env_stack_top (pro_state_ref , pro_env_stack *)
Returns:
The top environment of the stack.
References pro_env_stack::top, and pro_env_stack_node::value.