prosopon: src/pro_constructor.c File Reference
src/pro_constructor.c File Reference
#include "prosopon/core.h"
#include "pro_env.h"
#include "pro_common.h"
#include "pro_object.h"
#include "pro_lookup.h"
Functions
PRO_API pro_error pro_constructor_create (pro_state_ref s, pro_constructor *c, pro_ref ud, PRO_OUT pro_ref *constructor)
PRO_API pro_error pro_constructor_call (pro_state_ref s, pro_ref constructor, pro_ref arguments, PRO_OUT pro_ref *result)
Function Documentation
PRO_API pro_error pro_constructor_call (pro_state_ref , pro_ref constructor, pro_ref args, PRO_OUT pro_ref * result)
Calls a constructor with a list of arguments.
Parameters:
constructor The reference to the constructor to call.
args A list of lookups to pass to the constructor.
[out] result The result from the constructor.
Returns:
PRO_OK if successful PRO_INVALID_STATE if constructor does reference a constructor. PRO_CONSTRUCTOR_ERROR if the constructor call fails.
References pro_object::constructor, PRO_API_ASSERT, PRO_API_ASSERT_STATE, PRO_API_ASSERT_TYPE, PRO_CONSTRUCTOR_ERROR, PRO_CONSTRUCTOR_TYPE, pro_dereference(), PRO_EMPTY_REF, pro_env_create(), pro_env_release(), PRO_INVALID_OPERATION, pro_lookup_equal(), PRO_OK, pro_pop_env(), pro_push_env(), and pro_object::value.
PRO_API pro_error pro_constructor_create (pro_state_ref , pro_constructor * impl, pro_ref ud, PRO_OUT pro_ref * out_ref)
Creates a new constructor.
Parameters:
impl A function that constructs an object and returns a referance. Must not be null. The env that the constructor is created in will be current when this is called.
ud User data that is passed to the constructor function. May be PRO_EMPTY_REF.
[out] out_ref A reference to the new constructor with a reference count of 1.
Returns:
PRO_OK if successful PRO_INVALID_OPERATION if the state is not valid or id is null. if impl is null.
References pro_object::constructor, PRO_API_ASSERT, PRO_API_ASSERT_STATE, PRO_CONSTRUCTOR_TYPE, pro_get_env(), PRO_INVALID_OPERATION, pro_lookup_new(), pro_object_new(), PRO_OK, pro_retain(), and pro_object::value.